### ISSUE TITLE
Use raw values as services

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#1]
Users should be able to add raw values as services to reference.

```
dsn:
    value: 'dbi:mysql:mydb'
dbuser:
    value: "mysql"
dbpass:
    value: "12345"
dbh:
    class: DBI
    method: connect
    args:
        - { ref: dsn }
        - { ref: dbuser }
        - { ref: dbpass }
```

Instead of "class", "method", and "args", a service can specify a "value" that will be returned whenever the service is referenced. This can help make configuration containers that can be consumed by other containers.
