### ISSUE TITLE
Allow deep references of data structures

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#2]
It would be nice to be able to reach into a data structure and pull out only a section to reference, like so:

```
config:
    value:
        db:
            dsn: 'dbi:mysql:mydb'
            user: 'mysql'
            pass: '12345'
        cache: 
            driver: 'Memory'
dbh:
    class: DBI
    method: connect
    args:
        - { ref: config, path: 'db/dsn' }
        - { ref: config, path: 'db/user' }
        - { ref: config, path: 'db/pass' }
```

This makes it easier to use data structures with references, for when we have to fit existing configuration files into our services.

Ideally, we would use either the Data::Path or the Data::DPath or another CPAN module, but I can't decide which one is better...
