### ISSUE TITLE
Multiple Methods / Method Chaining

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#23]
I'm hesitant about this one, because it's complicated, but here goes:

File::Find::Rule is an excellent way of finding files to work on, but it requires multiple method calls in order for its object to be built to specification.

I propose the following syntax for this:

```
zip_files:
    class: File::Find::Rule
    lifecycle: factory
    method:
        - name: new
        - name: file
        - name: name
          args: '*.zip'
```

This is roughly equivalent to:

```
my $svc = File::Find::Rule->new; # the first member of @method
$svc->file; # the second member of @method
$svc->name( '*.zip' ); # the third member of @method
```

Another way of doing File::Find::Rule is with method chaining, which can be added like so:

```
rar_files:
    class: File::Find::Rule
    lifecycle: factory
    method:
        - name: new
        - name: file
          return: chain
        - name: name
          args: '*.rar'
          return: chain
```

This is roughly equivalent to:

```
my $svc = File::Find::Rule->new->file->name( '*.rar' );
```

They can be mixed and matched:

```
7z_files:
    class: File::Find::Rule
    lifecycle: factory
    method:
        - name: new
        - name: file
          return: chain
        - name: name
          args: '*.7z'
```

This is roughly equivalent to:

```
my $svc = File::Find::Rule->new->file;
$svc->name( '*.7z' );
```

So if your object needs multiple method calls to be fully initialized, here is how to do it. If it does method chaining (like DBIx::Class::ResultSet), this is also how you do it.

I'm not sure if "return: chain" is the best way to do it, but I want to avoid "chain: 1" at any cost. "type: chain" is also rather ambiguous. "return: chain" says what's happening, but "chain" could also be "keep" and work on regular values.
