### ISSUE TITLE
File paths relative to Share dirs

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#24]
Got another fun feature!

I need to be able to specify file paths relative to share directories. I've got a bunch of loosely-coupled module dists and they must grab configuration files from each other.

This ties into #3.

One proposed solution:

```
# /usr/lib/perl5/site_perl/5.12.1/auto/share/dist/My-Module/db_config.yml
dsn: dbi:SQLite:name.db

# wire.yml
config:
    class: BeamX::Service::Config::Any
    args:
        - { $dist: 'My-Module', $path: 'db_config.yml' }
```

The $dist/$path combo would return the path to the file in question. Then the BeamX::Service::Config::Any would load the file as a service to be used by other things.

This would have to work like any other reference, like when creating child containers:

```
# /usr/lib/perl5/site_perl/5.12.1/auto/share/dist/My-Module/db_wire.yml
dbh:
    class: DBI
    method: connect
    args:
        - 'dbi:SQLite:name.db'

# wire.yml
db:
    class: Beam::Wire
    args:
        file: { $dist: 'My-Module', $path: 'db_wire.yml' }
```

I can think of some other options (use a URI syntax, like $share:/My-Module/db_wire.yml), but they'd require more special-casing than our current reference syntax (which is "if all the hash keys start with $, we're in a reference of some kind").
