### ISSUE TITLE
Anonymous Inline References

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#25]
Instead of doing:

```
zip_files:
    class: File::Find::Rule
    lifecycle: factory
    method:
        - name: new
        - name: file
        - name: name
          args: '*.zip'
files_to_do:
    class: My::Todo::Files
    args:
        - { $ref: zip_files }
```

We should be able to do:

```
files_to_do:
    class: My::Todo::Files
    args:
        - $class: File::Find::Rule
          $method:
              - name: new
              - name: file
              - name: name
                args: '*.zip'
```

This will solve the problem with one service that depends on a lot of services that must be configured specifically for that one service. Instead of spreading them throughout the file, they can all be configured in one area.

All the usual service configuration should apply, the only rule is that in order for a certain hash to be treated as a reference or meta-hash of some kind it must prefix all of its keys with the meta-prefix.
