### ISSUE TITLE
Add method to build a path relative to the config file

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#36]
A lot of things need paths. Those paths should be able to be relative to the config file.

I'm thinking something like:

```
logger:
    class: Log::Dispatch
    args:
        - File
        - filename
        - { $file: var/log/mylog }
```

and/or

```
log_dir:
    path: var/log
logger:
    class: Log::Dispatch
    args:
        - File
        - filename
        - { $ref: log_dir }
```

This helps make a generic way of building paths, pulling out the special way that child containers do it.
