### ISSUE TITLE
Call methods on services as references

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#4]
We should be able to call a method on a service in a reference. This would let us use accessors as services.

``` perl
package Foo;
has greeting => ( is => 'ro', required => 1 );
package Bar;
has greeting => ( is => 'ro', required => 1 );
```

```
foo:
    class: Foo
    args:
        greeting: "Hello, World!"
bar:
    class: Bar
    args:
        greeting: { ref: foo, method: greeting }
```

We are probably going to want to be able to pass "args" to the method, but I can see that getting quickly out of hand.

``` perl
package Foo;
has greeting => ( is => 'ro', required => 1 );
sub greet {
    my ( $self, $name ) = @_;
    return join " ", $self->greeting, $name;
}
package Bar;
has greeting => ( is => 'ro', required => 1 );
```

```
foo:
    class: Foo
    args:
        greeting: "Hello, "
bar:
    class: Bar
    args:
        greeting: { ref: foo, method: greet, args: "Preaction" }
```

We should support any number of args, either a single scalar or an arrayref, and let the user find the practical limit.
