### ISSUE TITLE
Use $ for meta-tags everywhere

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#43]
We've got two weird things:

1) When declaring a service, we use "class", "args", "method", "sub", etc... but when declaring a dependency, we use "$class", "$args", "$method", "$sub", etc... I think we should use the "$prefix" version everywhere.

2) If we do that, we don't need to use "$args" if the object's constructor takes key-value arguments.

```
myobj:
    class: MyObject
    args:
        foo: bar
        baz: fuzz
```

Would become:

```
myobj:
    $class: MyObject
    foo: bar
    baz: fuzz
```

And `$args` only needs to be dragged out when it isn't key/value pairs (an array, arraryref, or hashref)

**Comment by preaction** [comment]
We could have both work, in theory. In the "service" case, if we see a prefixed attribute, it's the new syntax. In the "dependency" case, if we see an unprefixed attribute, it's the new syntax.

We should probably avoid supporting it forever, bu I'm not sure... I hate having to update because dependencies...

**Comment by preaction** [comment]
There are some edge cases to consider:

```yaml
plugin:
    baz:
        $class: My::Plugin::Baz
    foo:
        $class: My::Plugin::Foo
    class:
        $class: My::Plugin::Class
```

If I ask for `$wire->get( 'plugin' )`, should it try to instanciate it? It has a class, but it also has other, unknown stuff...

There are also straight-up ambiguities. But we don't want to get into a Makefile situation...

I'm tempted to, if someone reports a problem, allow a backcompat option to the constructor that will allow old containers to work.

**Comment by preaction** [comment]
I think if we're extremely careful and precise and well-tested, we can make this work, and then remove it for 2.0

**Comment by preaction** [comment]
I don't like the ambiguity of mixing meta tags and non-meta tags, so just force meta tags everywhere.

**Comment by preaction** [comment]
I've flip-flopped on mixing meta and non-meta tags, because allowing multiple ways of specifying a service is nice. In this example, we can specify a service as a string, as a hashref, or as a full object.

```yaml
source: /foo/bar/baz
```
```yaml
source:
    url: /foo/bar/baz
```
```yaml
source:
    $class: Cradle::Source::Svn
    url: /foo/bar/baz
```
```perl
# script.pl
my $wire = Beam::Wire->new( ... );
my $source = $wire->get( 'source' );
if ( !ref $source ) {
    $source = Cradle::Source::Git->new( url => $source );
}
elsif ( !blessed $source ) {
    $source = Cradle::Source::Git->new( %$source );
}
```

This makes the config files more powerful and easier to write for end-users.
