### ISSUE TITLE
Change `$method` in value dependency to `$call`

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#47]
`$call` calls the sub, and we can do currying by passing a hashref or something, like:

```yaml
foo:
    class: Foo

bar:
    class: Bar
    args:
        foo:
            $ref: foo
            $call: foo

        foosbar:
            $ref: foo
            $call:
                bar:
                    - baz
```

This way the `$method` has the same meaning as it does everywhere, it is the method to call on the `$class`.
