### ISSUE TITLE
Use Beam::Emitter to emit events during object creation

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#5]
The entire reason that Beam is a framework is that the modules work together!

The Beam::Wire should emit events after it is fully created, and after it creates a service (but not after every time a service is requested).

Child containers should bubble their events up to parent containers.

**Comment by preaction** [comment]
Also, it's hard to configure this via the config file, considering the config file needs to already exist. So the only use this has is for inner containers (maybe).

... Unless we allow the magic ref syntax in the main container as well... like...

```yaml
service:
    class: My::Service
$on:
    create_container:
        $ref: service
        $method: on_container_created
```

This would magically make an eager service, but more importantly, will give the service its own container, if for some reason it needed it.
