### ISSUE TITLE
Allow Beam::Emitter events to be configured in the container

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#6]
In order to keep everything as lazy as possible, allow Beam::Emitter events to be configured using the container. Then, only after a service is created will its event listeners be registered.

```perl
package Listener;
use Moo;
sub on_alert {
    my ( $self, $event ) = @_;
    # do something
}
package Emitter;
use Moo;
extends 'Beam::Emitter';
sub alert {
    my ( $self, $message ) = @_;
    $self->emit( 'alert' );
}
```

    listener:
        class: Listener
    emitter:
        class: Emitter
        on: 
            alert: { ref: listener, method: on_alert }

Now, calling $emitter->alert; will call Listener's on_alert method.

**Comment by preaction** [comment]
I now have a good use for this: preaction/Statocles#78

**Comment by preaction** [comment]
"on" is a fucking reserved word in YAML. Problem 1.

arrays of hashes can't have quoted keys or non-word characters in the keys, problem 2 (partially fixed in ingy/yaml-pm#146)

I'm going to adjust the data structure a bit to open up some options

**Comment by preaction** [comment]
A single listener:

```
emitter:
    class: Emitter
    on: 
        alert:
            $ref: listener
            $method: on_alert
```

Multiple listeners (array of hashes)
```
emitter:
    class: Emitter
    on: 
        - alert:
            $ref: listener
            $method: on_alert
```

Multiple listeners (hash of arrays) (this is broken with YAML.pm, but works for YAML::XS and YAML::Tiny).
```
emitter:
    class: Emitter
    on: 
        alert: 
            - $ref: listener
              $method: on_alert
```
