### ISSUE TITLE
Allow `$class` to be specified via a reference

### ISSUE THREAD

**Issue by djerius** [preaction/Beam-Wire#71]
I have a class generator based on [`Package::Variant`](https://metacpan.org/pod/Package::Variant) and I'd like to use that to generate a class name which can be used elsewhere in a configuration.  Something akin to this:

```
class_name:
  class: 'Package::Variant'
  method:
    - method: build_variant_of
      args:
       - 'MyVariant::Base'
       - other_variant_args
thing :
  class:
    $ref: class_name  
  args:
     - arg1
```
Or, even more simply:
```
class_name: MyVariantPackage

thing1 :
  class:
    $ref: class_name  
  args:
     - arg1

thing2:
  class:
    $ref: class_name  
  args:
     - arg2

```
Where `class_name` could also be set from user code via the `Beam::Wire::set` method.
