### ISSUE TITLE
[question] How to access objects not managed by a beam wire instance?

### ISSUE THREAD

**Issue by XSven** [preaction/Beam-Wire#74]
I wanted to configure a URI instance in yml and use beam wire to load it. I am using the **multiple constructor method approach** and I have problems with the configuration of the URI::query_form() method. One way to call this method is to pass a hash and that is what I try to use. Unfortunately the hash values are dynamic and refer to fields of other objects ($component, $repository) not managed by beam wire. How can I refer to such fields from the yml container. This is the configuration that of course does not work

```
download-url:
  class: URI
  method:
    - method: new
    - method: scheme
      args:
        - http
    - method: path_segments
      args:
        - nexus
        - service
        - local
        - artifact
        - maven
        - redirect
    - method: query_form
      args:
        g: $component->groupId
        a: $component->artifactId
        v: $component->version
        c: $component->classifier
        p: $component->packaging
        r: $repository->name
```

**Comment by XSven** [comment]
After carefully reading the beam wire documentation, I have noticed that the [services attribute](https://metacpan.org/pod/Beam::Wire#services) solves my problem. I have added the runtime objects giving them the names **injected-component** and **injected-repository** to the services cache. 

```
download-url:
  class: URI
  method:
    - method: new
    - method: scheme
      args:
        - http
    - method: path_segments
      args:
        - nexus
        - service
        - local
        - artifact
        - maven
        - redirect
    - method: host
      args:
        - $ref: injected-repository
          $call: host
    - method: query_form
      args:
        g:
          $ref: injected-component
          $call: groupId
        a:
          $ref: injected-component
          $call: artifactId
        v:
          $ref: injected-component
          $call: version
        c:
          $ref: injected-component
          $call: classifier
        p:
          $ref: injected-component
          $call: packaging
        r:
          $ref: injected-repository
          $call: name
```

My question/interest has changed now: How can I change the scope of the **download-url** service object from singleton (cached) to prototype (not cached)? I would like to get a new URI object, if I am calling

`my $url = $wire->get('download-url');`
