### ISSUE TITLE
[question] constructor with unusual args

### ISSUE THREAD

**Issue by XSven** [preaction/Beam-Wire#76]
The [Log::Log4perl::Appender](https://metacpan.org/pod/Log::Log4perl::Appender) constructor has a single positional parameter (the dispatcher class name)  and  a hash (not hashref) of named parameters that refers to the constructor attributes of the dispatcher class. How can I configure such an appender object in Beam::Wire?

This works

```
FILE-appender:
  class: Log::Log4perl::Appender
  args:
    - Log::Log4perl::Appender::File
    - name
    - FILE
    - filename
    - file.log
```

but it is awful.
