### ISSUE TITLE
Service inheritance

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#8]
In order to change only that minimum that needs to change between services, there should be a way to inherit properties from a service:

```
foo_base:
    class: Foo
    args:
        greeting: "Hello"
        object: "World"
es:
    extends: foo_base
    args: { greeting: "Hola" }
fr:
    extends: foo_base
    args: { greeting: "Bonjour" }
```

I'm not sure if it should be "extends" or "parent" or "base" (extends keeps up the "use the same keywords as Moose/Perl6" thing going though).

Unfortunately, this seems like it would only work well with hashrefs of arguments, not with arrayrefs of arguments. As always, I'm open to suggestions.

And this has to be one of the last things. I think we're reaching the limit of the number of features we can pack into this thing.
