### ISSUE TITLE
Lifecycle options

### ISSUE THREAD

**Issue by preaction** [preaction/Beam-Wire#9]
Sometimes we don't want a singleton. Singletons can be especially dangerous when using values as services (if somebody casually changes the value, everyone else's reference to that value gets changed).

```
dsn:
    value: 'dbi:SQLite:data.db'
    lifecycle: factory
dbh:
    class: DBI
    method: connect
    lifecycle: singleton
    args:
        - { ref: dsn }
```

The "factory" lifecycle would ensure that a new object or a new copy would be created every time it was requested (`$container->get( 'dsn' )` would always call `create_service()`, `create_service()` would never add the item to the `services` hash).

I'm not sure if "factory" is the best name for this. It's descriptive, but what Perl programmer uses factories? I don't think booleans are easy to read, so `factory: 1` or `clone: 1` would probably not be a good idea. Having a default of true is worse, so `singleton: 0` or `cache: 0` would probably also not be a good idea.

The "singleton" lifecycle is the default behavior, and is the current behavior.
